server:
  port: 8080

spring:
  security.oauth2.resourceserver.jwt.public-key-location: classpath:public.txt
  application.name: gts-gateway-service
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      httpclient:
        connect-timeout: 15
        response-timeout: 120
      routes:
        - id: gts-core-service
          uri: lb://gts-core-service
          predicates:
            - Path=/core/api/**
        - id: gts-report-service
          uri: lb://gts-report-service
          predicates:
            - Path=/report/api/**

eureka:
  instance:
    instanceId: ${spring.application.name}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://localhost:8761/eureka
