logging.level.org.springframework: info
server.port: 8080

#using local public-key or jwkSetUri
#spring.security.oauth2.resourceserver.jwt.public-key-location: classpath:public-key.txt
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwkSetUri: ${JWK_URI:http://localhost:8000/auth/.well-known/jwks.json}
  application.name: gts-gateway-service
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      httpclient:
        connect-timeout: 15
        response-timeout: 120
      routes:
        - id: gts-core-service
          uri: lb://gts-core-service
          predicates:
            - Path=/core/**
        - id: gts-report-service
          uri: lb://gts-report-service
          predicates:
            - Path=/report/**
        - id: gts-auth-service
          uri: lb://gts-auth-service
          predicates:
            - Path=/auth/**

eureka:
  instance:
    instanceId: ${spring.application.name}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://localhost:8761/eureka
