version: '3.8'
services:
  postgresql:
    container_name: 'gts-postgres-db'
    image: postgres
    user: root
    networks:
      - gts_network
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./postgres/initial_db.sql:/docker-entrypoint-initdb.d/initial_db.sql

  discovery:
    container_name: 'gts-discovery-service'
    image: 'discovery-service:latest'
    user: root
    networks:
      - gts_network
    environment:
      JAVA_OPTS: '-Xms200m -Xmx512m'
    ports:
      - 8761:8761

  auth:
    container_name: 'gts-auth-service'
    image: 'auth-service:latest'
    user: root
    networks:
      - gts_network
    command: bash -c "mkdir -p /var/log/gts_be"
    environment:
      DISCOVERY_ADDRESS: discovery
      DB_HOST: postgresql
      JAVA_OPTS: '-Xms200m -Xmx512m'
    depends_on:
      - discovery
      - postgresql

  gateway:
    container_name: 'gts-gateway-service'
    image: 'gateway-service:latest'
    user: root
    networks:
      - gts_network
    environment:
      DISCOVERY_ADDRESS: discovery
      JWK_URI: auth
      JAVA_OPTS: '-Xms200m -Xmx512m'
    ports:
      - 8080:8080
    depends_on:
      - discovery
      - auth

  core_1:
    container_name: 'gts-core_1-service'
    image: 'core-service:latest'
    user: root
    networks:
      - gts_network
    environment:
      DISCOVERY_ADDRESS: discovery
      DB_HOST: postgresql
      JAVA_OPTS: '-Xms200m -Xmx512m'
    depends_on:
      - discovery
      - postgresql

  core_2:
    container_name: 'gts-core_2-service'
    image: 'core-service:latest'
    user: root
    networks:
      - gts_network
    environment:
      DISCOVERY_ADDRESS: discovery
      DB_HOST: postgresql
      JAVA_OPTS: '-Xms200m -Xmx512m'
    depends_on:
      - discovery
      - postgresql

  report:
    container_name: 'gts-report-service'
    image: 'report-service:latest'
    user: root
    networks:
      - gts_network
    environment:
      KAFKA_SERVER: kafka
      DISCOVERY_ADDRESS: discovery
      JAVA_OPTS: '-Xms200m -Xmx512m'
    depends_on:
      - discovery
      - kafka

  logger:
    container_name: 'gts-logger-service'
    image: 'logger-service:latest'
    user: root
    networks:
      - gts_network
    environment:
      KAFKA_SERVER: kafka
      DISCOVERY_ADDRESS: discovery
      JAVA_OPTS: '-Xms200m -Xmx512m'
    depends_on:
      - discovery
      - kafka

  zookeeper:
    image: zookeeper:3.6.2
    user: root
    networks:
      - gts_network
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    user: root
    networks:
      - gts_network
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

networks:
  gts_network:
    driver: bridge